global:
  scrape_interval: 2s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'mysql_exporter'
    static_configs:
      - targets:
        - 'mysql-exporter:9104'
